name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip openjdk-17-jdk autoconf automake cmake pkg-config libffi-dev libssl-dev wget unzip

      - name: Install Buildozer & Python Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArmorMixer-APK
          path: bin/*.apk
          
