name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip openjdk-17-jdk autoconf automake cmake pkg-config libffi-dev libssl-dev wget unzip

      - name: Install Buildozer & Python Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK & Fix AIDL Not Found
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk-tools.zip
          unzip -q sdk-tools.zip -d android-sdk
          mkdir -p android-sdk/cmdline-tools/latest
          mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArmorMixer-APK
          path: bin/*.apk
          
